esphome:
  name: esptoyv2
  friendly_name: ESPToy v2
  
  # add mac address onto end of name (if multiple esptoys are on network)
  name_add_mac_suffix: true

esp8266:
#  board: esp01_1m
  board: esp12e

# Enable logging
logger:
  baud_rate: 0

ota:
 - platform: esphome
   password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPToy_v2"
    password: !secret api_password

captive_portal:
 
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200

  # this shows raw bytes in log (can be viewed in terminal over wifi)
  debug:
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

  actions:
    - action: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'


light:
# built in board LED (blue)
  - platform: status_led
    name: "Status LED"
    pin: 
      number: GPIO2
      inverted: true

# github says WS2812 [https://github.com/rayshobby/esptoy]
# schematic says WS2813
  - platform: neopixelbus
    type: GRB
    variant: WS2813
    pin: GPIO13
    num_leds: 1
    name: "NeoPixel Light"

# buzzer
output:
  - platform: esp8266_pwm
    pin: GPIO15
    id: rtttl_out

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'


    
# push button
binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode:
        input: true
      inverted: true
    name: Push Button
    id: pushbutton01
    filters:
      - delayed_on_off: 100ms
    publish_initial_state: true

# Example configuration entry
sensor:
  - platform: adc
    pin: GPIO17
    name: "Brightness"
    update_interval: 10s
    
# play a song
switch:
  - platform: template
    id: range
    name: "Play song"
    optimistic: true
    turn_on_action: 
      - rtttl.play: 'scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b'